name: RadiantMCPlugin
version: ${project.version}
author: Davis Mariotti
main: com.davismariotti.radiantmc.RadiantMCPlugin
api-version: 1.13

commands:
  nick:
    description: Sets nickname
  removenick:
    description: Removes nickname
  lastlogin:
    description: Finds who logged in last
  motd:
    description: Reads out the motd
  nethercoords:
    description: Finds the nether or overworld coordinates for your location
